### ISSUE TITLE
Random reboot system 

### ISSUE THREAD

**Issue by viktorpovh28** [greenforce-project/kernel_xiaomi_spes_sm6225#2]
Random crash of the modem Appears almost every day with a poor level of cellular communication . This is definitely kernel panic

**Comment by viktorpovh28** [comment]
This method fix crash or reboot
[https://review.lineageos.org/c/LineageOS/android_kernel_xiaomi_sm8250/+/319750](url)

**Comment by viktorpovh28** [comment]
<3>[45698.646324] icnss: Received early crash indication from FW
<6>[45698.646345] [irq/35][0xfb1f347901][09:26:10.604155] wlan: [220:I:HDD] wlan_hdd_pld_uevent: 1907: Received firmware down indication
<6>[45698.646376] [irq/35][0xfb1f347b89][09:26:10.604189] wlan: [220:I:IPA] wlan_ipa_uc_disable_pipes: 1379: IPA WDI Pipes are already deactivated
<6>[45698.646385] [irq/35][0xfb1f347c25][09:26:10.604197] wlan: [220:I:WMI] WMI Stop
<3>[45698.883230] Fatal error on modem!
<3>[45698.883259] modem subsystem failure reason: EX:kernel:0x0::0x0:PC=0xc0c6537c.
<6>[45698.883269] subsys-restart: subsystem_restart_dev(): Restart sequence requested for modem, restart_level = SYSTEM.
<6>[45698.883316] memshare soc:qcom,memshare: memshare: notifier_cb processed for code: 9
<3>[45698.883338] Ramdump(ramdump_microdump_modem): No consumers. Aborting..
<6>[45698.883342] microdump_modem_notifier_nb: do_ramdump() failed
<0>[45698.983499] Kernel panic - not syncing: subsys-restart: Resetting the SoC - modem crashed.
<4>[45698.983512] CPU: 0 PID: 25893 Comm: kworker/0:4 Tainted: G S      W         4.19.317-greenforce-g3c3d9e7b9994 #1
<4

**Comment by fadlyas07** [comment]
Yes, I will pick that commit thanks bro.
